#!/usr/bin/env bash
# AiCMR Test Accounts - Quick Command Reference

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║           AiCMR Test Accounts - Quick Reference               ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Test Account Credentials
echo "┌─ TEST ACCOUNTS ──────────────────────────────────────────────────┐"
echo "│                                                                   │"
echo "│ 1️⃣  ADMIN (Rank 5)                                               │"
echo "│     Email:    admin@aicmr.local                                  │"
echo "│     Password: Admin@123456                                       │"
echo "│                                                                   │"
echo "│ 2️⃣  MODERATOR (Rank 3)                                           │"
echo "│     Email:    moderator@aicmr.local                              │"
echo "│     Password: Moderator@123456                                   │"
echo "│                                                                   │"
echo "│ 3️⃣  MEMBER (Rank 1)                                              │"
echo "│     Email:    member@aicmr.local                                 │"
echo "│     Password: Member@123456                                      │"
echo "│                                                                   │"
echo "│ 4️⃣  GUEST (Rank 0)                                               │"
echo "│     Email:    testuser@example.com                               │"
echo "│     Password: Test@123456                                        │"
echo "│                                                                   │"
echo "└─────────────────────────────────────────────────────────────────┘"
echo ""

# Rank System
echo "┌─ RANK SYSTEM ────────────────────────────────────────────────────┐"
echo "│                                                                   │"
echo "│ Rank 5 (ADMIN)      → Full system access, all features           │"
echo "│ Rank 3 (MODERATOR)  → Content moderation, view user profiles     │"
echo "│ Rank 1 (MEMBER)     → Basic member features, post creation       │"
echo "│ Rank 0 (GUEST)      → View own profile only                      │"
echo "│                                                                   │"
echo "└─────────────────────────────────────────────────────────────────┘"
echo ""

# Testing URLs
echo "┌─ TESTING URLS ────────────────────────────────────────────────────┐"
echo "│                                                                   │"
echo "│ Frontend:        http://localhost:3000                           │"
echo "│ Login:           http://localhost:3000/login                     │"
echo "│ Profile:         http://localhost:3000/user/profile              │"
echo "│ Dashboard:       http://localhost:3000/dashboard (admin only)    │"
echo "│                                                                   │"
echo "│ Backend API:     http://localhost:8000                           │"
echo "│ API Docs:        http://localhost:8000/docs                      │"
echo "│ ReDoc:           http://localhost:8000/redoc                     │"
echo "│                                                                   │"
echo "└─────────────────────────────────────────────────────────────────┘"
echo ""

# API Testing
echo "┌─ API TESTING EXAMPLES ────────────────────────────────────────────┐"
echo "│                                                                   │"
echo "│ 🔓 Login:                                                         │"
echo "│    curl -X POST http://localhost:8000/api/v1/auth/login \\      │"
echo "│      -H 'Content-Type: application/json' \\                       │"
echo "│      -d '{                                                        │"
echo "│        \"email\": \"admin@aicmr.local\",                            │"
echo "│        \"password\": \"Admin@123456\"                               │"
echo "│      }'                                                           │"
echo "│                                                                   │"
echo "│ 👤 Get Current User:                                             │"
echo "│    curl -X GET http://localhost:8000/api/v1/users/me \\         │"
echo "│      -H 'Authorization: Bearer <access_token>'                   │"
echo "│                                                                   │"
echo "│ 🚪 Logout:                                                        │"
echo "│    curl -X POST http://localhost:8000/api/v1/auth/logout \\     │"
echo "│      -H 'Authorization: Bearer <access_token>' \\                │"
echo "│      -H 'Content-Type: application/json' \\                       │"
echo "│      -d '{\"refresh_token\": \"<refresh_token>\"}'                 │"
echo "│                                                                   │"
echo "└─────────────────────────────────────────────────────────────────┘"
echo ""

# Browser DevTools
echo "┌─ BROWSER DEVTOOLS (Console) ──────────────────────────────────────┐"
echo "│                                                                   │"
echo "│ // Check tokens                                                  │"
echo "│ localStorage.getItem('access_token')                             │"
echo "│ localStorage.getItem('refresh_token')                            │"
echo "│                                                                   │"
echo "│ // Decode JWT                                                    │"
echo "│ const jwt = localStorage.getItem('access_token');                │"
echo "│ const payload = JSON.parse(atob(jwt.split('.')[1]));             │"
echo "│ console.log(payload);                                            │"
echo "│                                                                   │"
echo "│ // Clear all tokens                                              │"
echo "│ localStorage.clear()                                             │"
echo "│                                                                   │"
echo "└─────────────────────────────────────────────────────────────────┘"
echo ""

# Testing Scenarios
echo "┌─ QUICK TEST SCENARIOS ────────────────────────────────────────────┐"
echo "│                                                                   │"
echo "│ ✅ Test Admin Access:                                            │"
echo "│    1. Login with admin@aicmr.local / Admin@123456                │"
echo "│    2. Go to /dashboard → should work                             │"
echo "│    3. Logout → should redirect to /login                         │"
echo "│                                                                   │"
echo "│ ✅ Test Member Access:                                           │"
echo "│    1. Login with member@aicmr.local / Member@123456              │"
echo "│    2. Go to /dashboard → should REDIRECT                         │"
echo "│    3. Go to /user/profile → should work                          │"
echo "│                                                                   │"
echo "│ ✅ Test Logout Flow:                                             │"
echo "│    1. Login with any account                                     │"
echo "│    2. Click 'Đăng xuất' button                                    │"
echo "│    3. Should redirect to /login                                  │"
echo "│    4. localStorage should be empty                               │"
echo "│    5. Open DevTools → check Network tab for logout call          │"
echo "│                                                                   │"
echo "│ ✅ Test Permission Boundaries:                                   │"
echo "│    1. Login as member (rank 1)                                   │"
echo "│    2. Try /user/admin → should redirect or error ❌              │"
echo "│    3. Try /dashboard → should redirect or error ❌               │"
echo "│    4. Login as admin and verify same routes work ✅              │"
echo "│                                                                   │"
echo "└─────────────────────────────────────────────────────────────────┘"
echo ""

# Files
echo "┌─ IMPORTANT FILES ────────────────────────────────────────────────┐"
echo "│                                                                   │"
echo "│ 📄 Documentation:  TEST_ACCOUNTS.md                              │"
echo "│ 🐍 Setup Script:   backend/scripts/create_test_accounts.py       │"
echo "│ 🔑 Auth Service:   frontend/src/lib/auth.ts                      │"
echo "│ 🔐 Auth Hooks:     frontend/src/hooks/useAuth.ts                 │"
echo "│ 🔓 Logout Page:    frontend/src/app/logout/page.tsx              │"
echo "│ 📱 Navbar:         frontend/src/components/layout/Navbar.tsx     │"
echo "│                                                                   │"
echo "└─────────────────────────────────────────────────────────────────┘"
echo ""

echo "💡 Tips:"
echo "   - For full documentation, see TEST_ACCOUNTS.md"
echo "   - Use admin account to test all features"
echo "   - Use other accounts to test permission boundaries"
echo "   - Check browser console for debug logs (with [Auth] prefix)"
echo "   - Check API docs at http://localhost:8000/docs for all endpoints"
echo ""
