from enum import Enum as PyEnum


GUEST_RANK = 0
MEMBER_RANK = 1
MODERATOR_RANK = 3
ADMIN_RANK = 5

DEFAULT_PAGE_SIZE = 10
MAX_PAGE_SIZE = 100
DEFAULT_USER_LIST_LIMIT = 10

PASSWORD_RESET_EXPIRE_MINUTES = 15

MIN_PASSWORD_LENGTH = 8

RATE_LIMIT_LOGIN = "20/minute"
RATE_LIMIT_REGISTER = "10/minute"
RATE_LIMIT_PASSWORD_RESET = "10/minute"

CACHE_INSTALL_STATUS_SECONDS = 60
CACHE_USER_INFO_SECONDS = 300
CACHE_USER_LIST_SECONDS = 120
CACHE_SETTINGS_SECONDS = 300


ERROR_EMAIL_EXISTS = "Email already registered"
ERROR_USERNAME_TAKEN = "Username already taken"
ERROR_INVALID_CREDENTIALS = "Invalid email or password"
ERROR_INACTIVE_USER = "Inactive user"
ERROR_NOT_ENOUGH_PERMISSIONS = "Not enough permissions"


# Post Module Constants
class PostStatus(str, PyEnum):
    DRAFT = "draft"
    PUBLISHED = "published"
    ARCHIVED = "archived"


CACHE_POST_LIST_SECONDS = 300
CACHE_POST_DETAIL_SECONDS = 600
